### ISSUE TITLE
rails 3.2.*

### ISSUE THREAD

**Issue by joaomilho** [jsmestad/socialite#10]
Any idea when will socialite be ready for 3.2.*?
## 

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    socialite (>= 0) ruby depends on
      rails (~> 3.1.0) ruby

```
rails (3.2.7)
```

**Comment by jsmestad** [comment]
Adding support for this now with a good amount of other changes to support `omniauth >= 1.x`. Please use `gem 'socialite', git: 'git://github.com/jsmestad/socialite.git'` for now.

**Comment by joaomilho** [comment]
Wow. Cool man. I'll check it out. Do you have a step by step for configuring Facebook, Twitter... auths?

**Comment by jsmestad** [comment]
I am getting all this together while bringing the gem up-to-date with OmniAuth 1.1.x. Follow the PR #12
